### ISSUE TITLE
Back navigation and caching

### ISSUE THREAD

**Issue by tahola** [youtube/spfjs#405]
I am using **spfjs** like this :

```
spf.init({}); 
$(document).on("spfclick", function(e){
$('.navbar img.spinner').show();
$('.loading').show().html('Loadiing...'); 
});
```

This animation work fine when I am going forward (by clicking **.spf-link**) but when I use the back button **img.spinner** and **.loading** still showing, i guess this come from the cache of Firefox.

I have this issue on Firefox and sometime on Chrome Android.

Is there a better way to do this ? I like to remove the .loading at the end but **$(document).on("spfdone"..** doesnt seem to work.

Thanks

**Comment by DavidCPhillips** [comment]
Hi There,

The **'spfclick'** event only fires on actual clicks. For an animation that you want to occur on every navigation I'd suggest using **'spfrequest'** instead. It occurs regardless of the type of request, even if it's loaded from cache.

As for removing the loading style, **'spfdone'** is what you're looking for. It fires at the end of every navigation. I can't recreate any issues with it, so if you can create a small self contained example where it fails, I'd gladly take a look.

http://youtube.github.io/spfjs/documentation/events/

**Comment by tahola** [comment]
**spfrequest** work fine but I dont get anything from anything **spfdone** so i cant remove the loader, this is my code : 
```

$(document).on("spfrequest", function(e){
	console.log('spfrequest');
	$('.navbar img.spinner').show();
});

$(document).on("spfdone", function(e) {
	console.log('spfdone');
	$('.navbar img.spinner').hide();
});
```

Is there anything wrong ? Do I need to do something on the server server side ?

**Comment by DavidCPhillips** [comment]
Nope, that should be everything you need to do. I can create it on my side (with plain JS) with the following that works on forward and backward navigations.

document.addEventListener('spfdone', function(e){
  console.log('spfdone')
});

Is it possible that your other navigation work is clearing your listeners, or otherwise killing your navigation?

I could likely help more if you have a running example somewhere.

**Comment by tahola** [comment]
Still the same, I dont get anything from spfdone, maybe there is forget something, you can see a live example here http://urlgone.com/eea3d1/

**Comment by DavidCPhillips** [comment]
Ah, the issue is actually in your server. Sorry if I was misleading before, while there's nothing you need to do to enable 'spfdone', SPF in general requires that the server send back a **JSON** response to spf requests instead of HTML.

In your case, I can see that you're making requests with '?spf=navigate' on the URL, but returning plain HTML. SPF doesn't know how to parse that, so it falls back to a full page reload. That's why you see the 'spfrequest' event, but not the done.

Take a look at the documentation regarding responses:
http://youtube.github.io/spfjs/documentation/start/#return-responses
http://youtube.github.io/spfjs/documentation/responses/

**Comment by tahola** [comment]
I did it, now everything is much better and i get the spfdone event.

Thanks again and thank you for your awesome work.

**Comment by DavidCPhillips** [comment]
Cool! Glad to hear it.

**Comment by thomasmikkel** [comment]
How can I get the server to send back a JSON response?

**Comment by DavidCPhillips** [comment]
That's going to be entirely dependent on your server set up.

SPF sends the url params (e.g. ?spf=navigate) as an indicator to the server, but it's up to the server implementation to recognize those and switch from an HTML response to a JSON response.

I'm afraid I can't much more specific then that. Try taking a look at the demo app for a python based sample:

https://github.com/youtube/spfjs/blob/master/src/server/demo/app.py

**Comment by thomasmikkel** [comment]
Thanks for your answer, David.
