### ISSUE TITLE
Strange error when loading new page

### ISSUE THREAD

**Issue by jhonsore** [youtube/spfjs#420]
Hy guys,

fist of all, thanks youtube on providing this incredible source.

That's my problem:

I navigate normally through pages but for some reason sometimes everything breaks down showing just the json in my page.
Maybe i'm making something wrong, but all requests are the same and there is just a static json through all pages.

I recorded what is happening for evaluation:

https://youtu.be/uWKHw8voIlg

https://youtu.be/46i5nIV5m9w

Best regards.

**Comment by DavidCPhillips** [comment]
It's a bit hard to confirm through the video, but it looks like you're
running into the navigation limits.

For some background, the spf is really meant as an opportunistic framework.
It tries to do an spf navigation where possible, but if something goes
wrong (a bug in the JS, a bad request, etc.), it expects to be able to fall
back to a traditional page load. To distinguish these cases, it sends the
spf cgi param ('spf=navigate') when it wants a JSON response, and sends no
param when it loads traditionally.

With this in mind, the framework has a default limit of 20 navigations
before it falls back to a traditional page load. This is in place as a
safeguard against memory leaks or similar bugs.

https://github.com/youtube/spfjs/blob/29965379cc77bd546c8829611028e03309a36bf3/src/client/config.js#L40

Now, we do support a null navigation limit which will skip any limit
checks, but keep in mind that there are other code paths which trigger a
traditional reload. So the recommended approach is for the server to only
provide a JSON response when the spf=navigate cgi param is sent, and
traditional HTML otherwise.

**Comment by jhonsore** [comment]
Wow,

I clicked 21 times in links and page breaks. Everything is clear now!

Thanks for all!
